export const REQUEST_TASKS = 'REQUEST_TASKS';
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCEED = 'ADD_TASK_SUCCEED';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const SET_TASK_DONE = 'SET_TASK_DONE';
export const SET_TASK_DONE_FAILED = 'SET_TASK_DONE_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';
