// Task actions
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCEED = 'ADD_TASK_SUCCEED';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const SET_TASK_DONE = 'SET_TASK_DONE';
export const SET_TASK_DONE_FAILED = 'SET_TASK_DONE_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_CANCEL = 'EDIT_TASK_CANCEL';

export const CHANGE_TASK_TEXT = 'CHANGE_TASK_TEXT';
export const CHANGE_TASK_TEXT_FAILED = 'CHANGE_TASK_TEXT_FAILED';

// App actions
export const LOADING_SUCCEED = 'LOADING_SUCCEED';
export const LOADING_FAILED = 'LOADING_FAILED';
